-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'bb6e74891a634f2c' HASH 'c75e9e86cce2da507a2fc79cb7ddbab4c0bc0e19fec281b1213e030a844f17f7' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."CATEGORIA_INSTRUMENTO"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "DENOMINACION" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."CATEGORIA_INSTRUMENTO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");        
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORIA_INSTRUMENTO;   
INSERT INTO "PUBLIC"."CATEGORIA_INSTRUMENTO" VALUES
(1, 'Cuerda'),
(2, 'Viento'),
(3, 'Percusion'),
(4, 'Teclado'),
(5, 'Electronico'),
(6, 'Cuerdas'),
(7, 'Cuerda'),
(8, 'Cuerda'); 
CREATE MEMORY TABLE "PUBLIC"."INSTRUMENTO"(
    "ALTA" BOOLEAN DEFAULT TRUE,
    "CANTIDAD_VENDIDA" INTEGER,
    "CATEGORIA_INSTRUMENTO" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 14) NOT NULL,
    "DESCRIPCION" CHARACTER VARYING(500),
    "COSTO_ENVIO" CHARACTER VARYING(255),
    "IMAGEN" CHARACTER VARYING(255),
    "INSTRUMENTO" CHARACTER VARYING(255),
    "MARCA" CHARACTER VARYING(255),
    "MODELO" CHARACTER VARYING(255),
    "PRECIO" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."INSTRUMENTO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");  
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.INSTRUMENTO;            
INSERT INTO "PUBLIC"."INSTRUMENTO" VALUES
(TRUE, 28, 1, 1, U&'Estas viendo una excelente mandolina de la marca Stagg, con un sonido muy dulce, tapa aros y fondo de tilo, y diapas\00f3n de palisandro. Es un instrumento ac\00fastico (no se enchufa) de cuerdas dobles (4 pares) con la caja ovalada y c\00f3ncava, y el m\00e1stil corto. Su utilizaci\00f3n abarca variados \00e1mbitos, desde rock, folk, country y ensambles experimentales.', 'G', 'nro10.jpg', 'Mandolina Instrumento Musical Stagg Sunburst', 'Stagg', 'M20', '2450'),
(TRUE, 10, 3, 2, U&'1 Pandereta - 32 sonajas met\00e1licas. M\00e1s de 8 a\00f1os vendiendo con 100 % de calificaciones POSITIVAS y clientes satisfechos !! ', '150', 'nro9.jpg', 'Pandereta Pandero Instrumento Musical ', 'DyM ventas', '32 sonajas', '325'),
(TRUE, 3, 3, 3, U&'Triangulo Musical de 24 Cent\00edmetros De Acero. ENVIOS POR CORREO O ENCOMIENDA: Se le deber\00e1n adicionar $40 en concepto de Despacho y el Costo del env\00edo se abonar\00e1 al recibir el producto en Terminal, Sucursal OCA o Domicilio', '250', 'nro8.jpg', 'Triangulo Musical 24 Cm Percusion', 'LBP', '24', '260'),
(TRUE, 2, 2, 4, 'BARCHIME CORTINA MUSICAL DE 25 BARRAS LATIN CUSTOM. Emitimos factura A y B', 'G', 'nro7.jpg', 'Bar Chimes Lp Cortina Musical 72 Barras ', 'FM', 'LATIN', '2250'),
(TRUE, 5, 3, 5, U&'Las calabazas utilizadas para nuestras artesan\00edas son sembradas y cosechadas por nosotros, quienes seleccionamos el mejor fruto para garantizar la calidad del producto y ofrecerle algo creativo y original.', '300', 'nro6.jpg', U&'Shekeres. Instrumento. M\00fasica. Artesan\00eda. ', U&'Azalea Artesan\00edas', 'Cuentas de madera', '850'),
(TRUE, 0, 4, 6, U&'Buen dia! Sale a la venta este Piano Alem\00e1n Neumeyer con candelabros incluidos. Tiene una talla muy bonita en la madera. Una pieza de calidad.', '2000', 'nro3.jpg', 'Antiguo Piano Aleman Con Candelabros. ', 'Neumeyer', 'Stratus', '17000'),
(TRUE, 5, 1, 7, U&'Material: Pl\00e1stico smil madera 4 Cuerdas longitud: 60cm, el mejor regalo para usted, su familia y amigos, adecuado para 3-18 a\00f1os de edad', 'G', 'nro4.jpg', 'Guitarra Ukelele Infantil Grande 60cm', 'GUITARRA', 'UKELELE', '500'),
(TRUE, 1375, 5, 8, U&'Organo Electr\00f3nico GADNIC T01. Display de Led. 54 Teclas. 100 Timbres / 100 Ritmos. 4 1/2 octavas. 8 Percusiones. 8 Canciones de muestra. Grabaci\00f3n y reproducci\00f3n. Entrada para Micr\00f3fono. Salida de Audio (Auriculares / Amplificador). Vibrato. Sustain Incluye Atril Apoya partitura y Micr\00f3fono. Dimensiones: 84,5 x 32,5 x 11 cm', 'G', 'nro2.jpg', 'Teclado Organo Electronico Musical Instrumento 54 Teclas ', 'GADNIC', 'T01', '2250'),
(TRUE, 15, 3, 9, U&'Estas viendo un excelente y complet\00edsimo set de percusion para ni\00f1os con estuche r\00edgido, equipado con los instrumentos mas divertidos! De gran calidad y sonoridad. Ideal para jardines, escuelas primarias, musicoterapeutas o chicos que se quieran iniciar en la m\00fasica de la mejor manera. Es un muy buen producto que garantiza entretenimiento en cualquier casa o reuni\00f3n, ya que esta equipado para que varias personas al mismo tiempo est\00e9n tocando un instrumento.', '300', 'nro1.jpg', U&'Instrumentos De Percusi\00f3n Ni\00f1os Set Musical Con Estuche ', 'KNIGHT', 'LB17', '2700'),
(TRUE, 380, 3, 10, U&'DESCRIPCI\00d3N: DE 1 A 3 A\00d1OS. EL SET INCLUYE 5 TAMBORES, PALILLOS Y EL PLATILLO TAL CUAL LAS FOTOS. SONIDOS REALISTAS Y F\00c1CIL DE MONTAR. MEDIDAS: 40X20X46 CM', '250', 'nro5.jpg', U&'Bater\00eda Musical Infantil Juguete Ni\00f1o 9 Piezas Palillos ', 'Bateria', 'Infantil', '850'),
(TRUE, 50, 6, 11, U&'Una guitarra el\00e9ctrica cl\00e1sica.', '15.00', 'guitarra.jpg', 'Guitarra', 'Fender', 'Stratocaster', '750.00'),
(TRUE, 28, 7, 12, U&'Estas viendo una excelente mandolina de la marca Stagg, con un sonido muy dulce, tapa aros y fondo de tilo, y diapas\00f3n de palisandro. Es un instrumento ac\00fastico (no se enchufa) de cuerdas dobles (4 pares) con la caja ovalada y c\00f3ncava, y el m\00e1stil corto. Su utilizaci\00f3n abarca variados \00e1mbitos, desde rock, folk, country y ensambles experimentales.', 'G', 'nro10.jpg', 'Mandolina Instrumento Musical Stagg Sunburst', 'Stagg', 'M20', '2450');           
INSERT INTO "PUBLIC"."INSTRUMENTO" VALUES
(TRUE, 28, 8, 13, U&'Estas viendo una excelente mandolina de la marca Stagg, con un sonido muy dulce, tapa aros y fondo de tilo, y diapas\00f3n de palisandro. Es un instrumento ac\00fastico (no se enchufa) de cuerdas dobles (4 pares) con la caja ovalada y c\00f3ncava, y el m\00e1stil corto. Su utilizaci\00f3n abarca variados \00e1mbitos, desde rock, folk, country y ensambles experimentales.', 'G', 'nro10.jpg', 'Mandolina Instrumento Musical Stagg Sunburst', 'Stagg', 'M20', '2450');             
CREATE MEMORY TABLE "PUBLIC"."MY_USER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FULL_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "ROLE" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."MY_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_86" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.MY_USER; 
INSERT INTO "PUBLIC"."MY_USER" VALUES
(1, 'admin@admin.com', 'Admin Admin', 'admin', 'ADMIN'),
(2, 'user@user.com', 'User User', 'user', 'USER'),
(3, 'juan.perez@example.com', U&'Juan P\00e9rez', 'password123', 'USER'),
(4, 'maria.garcia@example.com', U&'Mar\00eda Garc\00eda', 'securepassword', 'USER');          
CREATE MEMORY TABLE "PUBLIC"."PEDIDO"(
    "FECHA_PEDIDO" DATE,
    "TOTAL_PEDIDO" FLOAT(53),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "USER_ID" BIGINT
);            
ALTER TABLE "PUBLIC"."PEDIDO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8C" PRIMARY KEY("ID");      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PEDIDO;  
INSERT INTO "PUBLIC"."PEDIDO" VALUES
(DATE '2023-05-12', 150.75, 1, NULL),
(DATE '2023-06-15', 300.5, 2, NULL);             
CREATE MEMORY TABLE "PUBLIC"."PEDIDO_DETALLE"(
    "CANTIDAD" INTEGER,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "INSTRUMENTO_ID" BIGINT,
    "PEDIDO_ID" BIGINT
);    
ALTER TABLE "PUBLIC"."PEDIDO_DETALLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");               
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.PEDIDO_DETALLE;          
INSERT INTO "PUBLIC"."PEDIDO_DETALLE" VALUES
(2, 1, 11, NULL),
(1, 2, 12, NULL),
(3, 3, 13, NULL);         
CREATE MEMORY TABLE "PUBLIC"."PREFERENCEMP"(
    "STATUS_CODE" INTEGER NOT NULL,
    "ID" CHARACTER VARYING(255) NOT NULL
);               
ALTER TABLE "PUBLIC"."PREFERENCEMP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PREFERENCEMP;            
ALTER TABLE "PUBLIC"."MY_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" CHECK("ROLE" IN('ADMIN', 'USER')) NOCHECK;              
ALTER TABLE "PUBLIC"."INSTRUMENTO" ADD CONSTRAINT "PUBLIC"."FKIC8ATE9DMUNPB0NAXXU24NMKJ" FOREIGN KEY("CATEGORIA_INSTRUMENTO") REFERENCES "PUBLIC"."CATEGORIA_INSTRUMENTO"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."PEDIDO_DETALLE" ADD CONSTRAINT "PUBLIC"."FKOA5C7IKDPMIWN2AALF6AQSKWI" FOREIGN KEY("INSTRUMENTO_ID") REFERENCES "PUBLIC"."INSTRUMENTO"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."PEDIDO" ADD CONSTRAINT "PUBLIC"."FKDDYEP9VOPCEMFL3AS9BNK35XE" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."MY_USER"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."PEDIDO_DETALLE" ADD CONSTRAINT "PUBLIC"."FKHUVCQBD92KC4EQYPGQMYI17CB" FOREIGN KEY("PEDIDO_ID") REFERENCES "PUBLIC"."PEDIDO"("ID") NOCHECK;              
