SELECT EXTRACT(YEAR FROM FECHA_PEDIDO) AS ANIO,
       EXTRACT(MONTH FROM FECHA_PEDIDO) AS MES,
       SUM(CANTIDAD) AS CANTIDAD_INSTRUMENTOS_VENDIDOS
FROM PUBLIC.PEDIDO
JOIN PUBLIC.PEDIDO_DETALLE ON PUBLIC.PEDIDO.ID = PUBLIC.PEDIDO_DETALLE.PEDIDO_ID
GROUP BY ANIO, MES
ORDER BY ANIO, MES;

SELECT  
       EXTRACT(MONTH FROM FECHA_PEDIDO) AS MES,
       SUM(CANTIDAD) AS CANTIDAD_INSTRUMENTOS_VENDIDOS
FROM PUBLIC.PEDIDO
JOIN PUBLIC.PEDIDO_DETALLE ON PUBLIC.PEDIDO.ID = PUBLIC.PEDIDO_DETALLE.PEDIDO_ID
WHERE EXTRACT(YEAR FROM FECHA_PEDIDO)  = 2019
GROUP BY  MES
ORDER BY  MES;

